# Generated by Django 4.2.4 on 2023-08-22 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_cart_product_cartitem_cart_items_cart_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="cartitem", name="cart",),
        migrations.RemoveField(model_name="cartitem", name="product",),
        migrations.DeleteModel(name="Cart",),
        migrations.DeleteModel(name="CartItem",),
        migrations.DeleteModel(name="Product",),
    ]
