# Generated by Django 4.2.4 on 2023-09-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_cartitem_cart_remove_cartitem_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.CharField(default="N/A", max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.CharField(default="N/A", max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(default="N/A", max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(default="N/A", max_length=15),
        ),
    ]
