# Generated by Django 4.2.4 on 2023-09-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_profile_address_alter_profile_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.CharField(default=" ", max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(default=" ", max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(default=" ", max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(default=" ", max_length=15),
        ),
    ]
