# Generated by Django 4.2.4 on 2023-08-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="download_token",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="link_expiration",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
