# Generated by Django 4.2.4 on 2023-08-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_cartitem_download_token_cartitem_link_expiration"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="checked_out",
            field=models.BooleanField(default=False),
        ),
    ]
